# Generated by Django 2.2.1 on 2019-06-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_friend_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowed',
            name='when',
        ),
    ]
